import { lazy } from 'react'
import { MODULES_BY_KEY } from '../app/moduleRegistry'

export const Layout = lazy(() => import('../Layout'))
export const ServiceChooser = lazy(() => import('../common/ServiceChooser'))
export const Login = lazy(() => import('../pages/Login'))
export const Assistant = lazy(() => import('../pages/Assistant'))
export const Dashboard = lazy(() => import('../pages/Dashboard'))
export const Reports = lazy(() => import('../pages/Reports'))
export const Settings = lazy(() => import('../pages/Settings'))
export const Plans = lazy(() => import('../pages/Plans'))
export const Account = lazy(() => import('../pages/Account'))
export const Analytics = lazy(() => import('../pages/Analytics'))
export const Backup = lazy(() => import('../pages/Backup'))
export const Activity = lazy(() => import('../pages/Activity'))
export const BillingHome = lazy(() => import('../pages/billing/BillingHome'))
export const TxnForm = lazy(() => import('../pages/billing/TxnForm'))
export const Catalog = lazy(() => import('../pages/billing/Catalog'))
export const CashBank = lazy(() => import('../pages/billing/CashBank'))
export const BillingSettings = lazy(() => import('../pages/billing/BillingSettings'))
export const Users = lazy(() => import('../pages/Users'))
export const Integrations = lazy(() => import('../pages/Integrations'))
export const Insights = lazy(() => import('../pages/Insights'))
export const Broadcast = lazy(() => import('../pages/Broadcast'))
export const VideoCall = lazy(() => import('../pages/VideoCall'))
export const OperationsWorkspace = lazy(() => import('../services/operations/OperationsWorkspace'))

export const InteriorRoutes = lazy(MODULES_BY_KEY.interior.lazyRouteLoader)

export const WarehouseRoutes = lazy(MODULES_BY_KEY.warehouse.lazyRouteLoader)

export const SchoolRoutes = lazy(MODULES_BY_KEY.school.lazyRouteLoader)

export const HotelRoutes = lazy(MODULES_BY_KEY.hotel.lazyRouteLoader)
export const TravelRoutes = lazy(MODULES_BY_KEY.travel.lazyRouteLoader)
export const NewsRoutes = lazy(MODULES_BY_KEY.news.lazyRouteLoader)
export const JobsRoutes = lazy(MODULES_BY_KEY.jobs.lazyRouteLoader)
export const CommerceRoutes = lazy(MODULES_BY_KEY.commerce.lazyRouteLoader)
export const BankRoutes = lazy(MODULES_BY_KEY.bank.lazyRouteLoader)
export const MedicalRoutes = lazy(MODULES_BY_KEY.medical.lazyRouteLoader)
export const HomeServicesRoutes = lazy(MODULES_BY_KEY['home-services'].lazyRouteLoader)
