import { lazy } from 'react'
import { MODULES_BY_KEY } from '../app/moduleRegistry'

export const Layout = lazy(() => import('../Layout'))
export const ServiceChooser = lazy(() => import('../common/ServiceChooser'))
export const Login = lazy(() => import('../pages/Login'))
export const Assistant = lazy(() => import('../pages/Assistant'))
export const Dashboard = lazy(() => import('../pages/Dashboard'))
export const Reports = lazy(() => import('../pages/Reports'))
export const Settings = lazy(() => import('../pages/Settings'))
export const Plans = lazy(() => import('../pages/Plans'))
export const Account = lazy(() => import('../pages/Account'))
export const Analytics = lazy(() => import('../pages/Analytics'))
export const Backup = lazy(() => import('../pages/Backup'))
export const Activity = lazy(() => import('../pages/Activity'))
export const BillingHome = lazy(() => import('../pages/billing/BillingHome'))
export const TxnForm = lazy(() => import('../pages/billing/TxnForm'))
export const Catalog = lazy(() => import('../pages/billing/Catalog'))
export const CashBank = lazy(() => import('../pages/billing/CashBank'))
export const BillingSettings = lazy(() => import('../pages/billing/BillingSettings'))
export const Users = lazy(() => import('../pages/Users'))
export const Integrations = lazy(() => import('../pages/Integrations'))
export const Insights = lazy(() => import('../pages/Insights'))
export const Broadcast = lazy(() => import('../pages/Broadcast'))
export const VideoCall = lazy(() => import('../pages/VideoCall'))

export const InteriorRoutes = lazy(MODULES_BY_KEY.interior.lazyRouteLoader)

export const WarehouseRoutes = lazy(MODULES_BY_KEY.warehouse.lazyRouteLoader)

export const SchoolRoutes = lazy(MODULES_BY_KEY.school.lazyRouteLoader)

export const HotelHome = lazy(MODULES_BY_KEY.hotel.lazyRouteLoader)
export const HotelReservations = lazy(() => import('../services/hotel/HotelReservations'))
export const HotelRooms = lazy(() => import('../services/hotel/HotelRooms'))
export const HotelGuests = lazy(() => import('../services/hotel/HotelGuests'))
export const HotelHousekeeping = lazy(() => import('../services/hotel/HotelHousekeeping'))
export const HotelShell = lazy(() => import('../services/hotel/HotelShell'))

export const TravelHome = lazy(MODULES_BY_KEY.travel.lazyRouteLoader)
export const TravelDestinations = lazy(() => import('../services/travel/TravelDestinations'))
export const TravelPackages = lazy(() => import('../services/travel/TravelPackages'))
export const TravelGroupTrips = lazy(() => import('../services/travel/TravelGroupTrips'))
export const TravelCustomize = lazy(() => import('../services/travel/TravelCustomize'))
export const TravelMyTrips = lazy(() => import('../services/travel/TravelMyTrips'))

export const NewsHome = lazy(MODULES_BY_KEY.news.lazyRouteLoader)
export const NewsLatest = lazy(() => import('../services/news/NewsLatest'))
export const NewsBookmarks = lazy(() => import('../services/news/NewsBookmarks'))
export const NewsArticle = lazy(() => import('../services/news/NewsArticle'))
export const NewsTrending = lazy(() => import('../services/news/NewsTrending'))
export const NewsSearch = lazy(() => import('../services/news/NewsSearch'))
export const NewsCategory = lazy(() => import('../services/news/NewsCategory'))

export const JobsHome = lazy(MODULES_BY_KEY.jobs.lazyRouteLoader)
export const JobsSearch = lazy(() => import('../services/jobs/JobsSearch'))
export const JobsSaved = lazy(() => import('../services/jobs/JobsSaved'))
export const JobDetail = lazy(() => import('../services/jobs/JobDetail'))
export const JobsCompanies = lazy(() => import('../services/jobs/JobsCompanies'))
export const CompanyDetail = lazy(() => import('../services/jobs/CompanyDetail'))
export const JobsApplications = lazy(() => import('../services/jobs/JobsApplications'))
export const CandidateProfile = lazy(() => import('../services/jobs/CandidateProfile'))
export const JobApplicationFlow = lazy(() => import('../services/jobs/JobApplicationFlow'))

export const CommerceHome = lazy(MODULES_BY_KEY.commerce.lazyRouteLoader)
export const CommerceCategories = lazy(() => import('../services/commerce/CommerceCategories'))
export const CommerceProducts = lazy(() => import('../services/commerce/CommerceProducts'))
export const CommerceProductDetail = lazy(() => import('../services/commerce/CommerceProductDetail'))
export const CommerceCart = lazy(() => import('../services/commerce/CommerceCart'))
export const CommerceWishlist = lazy(() => import('../services/commerce/CommerceWishlist'))
export const CommerceOffers = lazy(() => import('../services/commerce/CommerceOffers'))
export const CommerceBrands = lazy(() => import('../services/commerce/CommerceBrands'))
export const CommerceSearch = lazy(() => import('../services/commerce/CommerceSearch'))
export const CommerceCheckout = lazy(() => import('../services/commerce/CommerceCheckout'))

export const BankHome = lazy(MODULES_BY_KEY.bank.lazyRouteLoader)
export const BankAccounts = lazy(() => import('../services/bank/BankAccounts'))
export const BankAccountDetail = lazy(() => import('../services/bank/BankAccountDetail'))
export const BankTransactions = lazy(() => import('../services/bank/BankTransactions'))
export const BankTransfers = lazy(() => import('../services/bank/BankTransfers'))
export const BankBeneficiaries = lazy(() => import('../services/bank/BankBeneficiaries'))
export const BankCards = lazy(() => import('../services/bank/BankCards'))
export const BankDeposits = lazy(() => import('../services/bank/BankDeposits'))
export const BankLoans = lazy(() => import('../services/bank/BankLoans'))
export const BankStatements = lazy(() => import('../services/bank/BankStatements'))
export const BankBills = lazy(() => import('../services/bank/BankBills'))
export const BankNotifications = lazy(() => import('../services/bank/BankNotifications'))
export const BankDocuments = lazy(() => import('../services/bank/BankDocuments'))
export const BankProfile = lazy(() => import('../services/bank/BankProfile'))
export const BankAdmin = lazy(() => import('../services/bank/BankAdmin'))

export const MedicalHome = lazy(MODULES_BY_KEY.medical.lazyRouteLoader)
export const MedicalDoctors = lazy(() => import('../services/medical/pages/MedicalDoctors'))
export const MedicalAppointments = lazy(() => import('../services/medical/pages/MedicalAppointments'))
export const MedicalPatients = lazy(() => import('../services/medical/pages/MedicalPatients'))
export const MedicalPatientDetail = lazy(() => import('../services/medical/pages/MedicalPatientDetail'))
export const MedicalPrescriptions = lazy(() => import('../services/medical/pages/MedicalPrescriptions'))
export const MedicalLabs = lazy(() => import('../services/medical/pages/MedicalLabs'))
export const MedicalBilling = lazy(() => import('../services/medical/pages/MedicalBilling'))
export const MedicalRecords = lazy(() => import('../services/medical/pages/MedicalRecords'))
export const MedicalNotifications = lazy(() => import('../services/medical/pages/MedicalNotifications'))
export const MedicalAdmin = lazy(() => import('../services/medical/pages/MedicalAdmin'))

export const HomeServicesHome = lazy(MODULES_BY_KEY['home-services'].lazyRouteLoader)
export const HomeServicesCategories = lazy(() => import('../services/home-services/pages/Categories'))
export const HomeServicesCategoryDetail = lazy(() => import('../services/home-services/pages/CategoryDetail'))
export const HomeServicesServiceDetail = lazy(() => import('../services/home-services/pages/ServiceDetail'))
export const HomeServicesSearch = lazy(() => import('../services/home-services/pages/Search'))
export const HomeServicesBookingFlow = lazy(() => import('../services/home-services/pages/BookingFlow'))
export const HomeServicesBookings = lazy(() => import('../services/home-services/pages/Bookings'))
export const HomeServicesBookingDetail = lazy(() => import('../services/home-services/pages/BookingDetail'))
export const HomeServicesOffers = lazy(() => import('../services/home-services/pages/Offers'))
export const HomeServicesAccount = lazy(() => import('../services/home-services/pages/Account'))
export const HomeServicesAddresses = lazy(() => import('../services/home-services/pages/Addresses'))
export const HomeServicesDatabaseCheck = lazy(() => import('../services/home-services/pages/DatabaseCheck'))
export const HomeServicesAddCategory = lazy(() => import('../services/home-services/pages/AddCategory'))
export const HomeServicesProDashboard = lazy(() => import('../services/home-services/pages/pro/ProDashboard'))
export const HomeServicesProRequests = lazy(() => import('../services/home-services/pages/pro/ProRequests'))
export const HomeServicesProJobs = lazy(() => import('../services/home-services/pages/pro/ProJobs'))
export const HomeServicesProJobDetail = lazy(() => import('../services/home-services/pages/pro/ProJobDetail'))
export const HomeServicesProEarnings = lazy(() => import('../services/home-services/pages/pro/ProEarnings'))
export const HomeServicesProProfile = lazy(() => import('../services/home-services/pages/pro/ProProfile'))
export const HomeServicesAdminDashboard = lazy(() => import('../services/home-services/pages/admin/AdminDashboard'))
export const HomeServicesAdminLiveOps = lazy(() => import('../services/home-services/pages/admin/AdminLiveOps'))
export const HomeServicesAdminBookings = lazy(() => import('../services/home-services/pages/admin/AdminBookings'))
export const HomeServicesAdminProfessionals = lazy(() => import('../services/home-services/pages/admin/AdminProfessionals'))
export const HomeServicesAdminFinance = lazy(() => import('../services/home-services/pages/admin/AdminFinance'))
