import type {
  InteriorProject, InteriorRoom, InteriorDesign, InteriorProduct,
} from './types'

export const PROJECT_SEED: InteriorProject[] = [
  {
    id: 'int-proj-1',
    name: 'Living Room Renovation',
    propertyType: 'Apartment',
    location: 'Mumbai, Maharashtra',
    totalArea: 320,
    budget: 250000,
    status: 'active',
    createdAt: '2026-07-28T10:00:00.000Z',
  },
  {
    id: 'int-proj-2',
    name: 'Master Bedroom Redesign',
    propertyType: 'Villa',
    location: 'Pune, Maharashtra',
    totalArea: 260,
    budget: 180000,
    status: 'active',
    createdAt: '2026-08-02T09:30:00.000Z',
  },
  {
    id: 'int-proj-3',
    name: 'Kitchen & Dining Upgrade',
    propertyType: 'House',
    location: 'Bengaluru, Karnataka',
    totalArea: 210,
    budget: 300000,
    status: 'completed',
    createdAt: '2026-06-15T12:00:00.000Z',
  },
]

export const ROOM_SEED: InteriorRoom[] = [
  {
    id: 'int-room-1',
    projectId: 'int-proj-1',
    name: 'Living Room',
    roomType: 'Living Room',
    length: 15,
    width: 12,
    height: 10,
    budget: 120000,
    notes: 'South-facing with a large balcony window.',
    createdAt: '2026-07-28T10:10:00.000Z',
  },
  {
    id: 'int-room-2',
    projectId: 'int-proj-1',
    name: 'TV Lounge Corner',
    roomType: 'Living Room',
    length: 10,
    width: 8,
    height: 10,
    budget: 60000,
    notes: 'Adjacent to the main living area.',
    createdAt: '2026-07-29T11:00:00.000Z',
  },
  {
    id: 'int-room-3',
    projectId: 'int-proj-2',
    name: 'Master Bedroom',
    roomType: 'Master Bedroom',
    length: 14,
    width: 12,
    height: 9,
    budget: 100000,
    notes: 'Needs a walk-in wardrobe corner.',
    createdAt: '2026-08-02T09:45:00.000Z',
  },
  {
    id: 'int-room-4',
    projectId: 'int-proj-3',
    name: 'Kitchen',
    roomType: 'Kitchen',
    length: 12,
    width: 10,
    height: 10,
    budget: 150000,
    createdAt: '2026-06-15T12:10:00.000Z',
  },
]

export const DESIGN_SEED: InteriorDesign[] = [
  {
    id: 'int-des-1',
    projectId: 'int-proj-1',
    roomId: 'int-room-1',
    name: 'Modern Living Room',
    style: 'Modern',
    color: 'Grey',
    budget: 120000,
    status: 'completed',
    favorite: true,
    saved: true,
    createdAt: '2026-07-30T14:00:00.000Z',
    currentVersion: 2,
    versions: [
      {
        id: 'int-ver-1-1',
        version: 1,
        style: 'Modern',
        color: 'Grey',
        budget: 120000,
        prompt: 'I want an L-shaped sofa, TV unit and warm lighting.',
        productIds: ['int-prod-1', 'int-prod-4', 'int-prod-9'],
        createdAt: '2026-07-30T14:00:00.000Z',
      },
      {
        id: 'int-ver-1-2',
        version: 2,
        style: 'Modern',
        color: 'Grey',
        budget: 128000,
        prompt: 'Make the sofa blue and add indoor plants.',
        productIds: ['int-prod-2', 'int-prod-4', 'int-prod-9', 'int-prod-14'],
        createdAt: '2026-07-30T15:30:00.000Z',
      },
    ],
  },
  {
    id: 'int-des-2',
    projectId: 'int-proj-1',
    roomId: 'int-room-1',
    name: 'Minimal Scandinavian Lounge',
    style: 'Scandinavian',
    color: 'Beige',
    budget: 98000,
    status: 'completed',
    favorite: false,
    saved: false,
    createdAt: '2026-07-30T16:00:00.000Z',
    currentVersion: 1,
    versions: [
      {
        id: 'int-ver-2-1',
        version: 1,
        style: 'Scandinavian',
        color: 'Beige',
        budget: 98000,
        prompt: 'Light wood tones and lots of natural light.',
        productIds: ['int-prod-3', 'int-prod-8', 'int-prod-11'],
        createdAt: '2026-07-30T16:00:00.000Z',
      },
    ],
  },
  {
    id: 'int-des-3',
    projectId: 'int-proj-2',
    roomId: 'int-room-3',
    name: 'Luxury Bedroom Suite',
    style: 'Luxury',
    color: 'White',
    budget: 100000,
    status: 'completed',
    favorite: true,
    saved: true,
    createdAt: '2026-08-03T10:00:00.000Z',
    currentVersion: 1,
    versions: [
      {
        id: 'int-ver-3-1',
        version: 1,
        style: 'Luxury',
        color: 'White',
        budget: 100000,
        prompt: 'Elegant, plush and premium finishes.',
        productIds: ['int-prod-6', 'int-prod-10', 'int-prod-12'],
        createdAt: '2026-08-03T10:00:00.000Z',
      },
    ],
  },
]

export const PRODUCT_SEED: InteriorProduct[] = [
  // Furniture
  { id: 'int-prod-1', name: 'Modern 3-Seater Sofa', category: 'Furniture', price: 55000, material: 'Fabric', color: 'Grey', width: '7 ft', depth: '3 ft', description: 'Compact L-shaped section with removable cushions.' },
  { id: 'int-prod-2', name: 'Blue Velvet Sofa', category: 'Furniture', price: 64000, material: 'Velvet', color: 'Blue', width: '7.5 ft', depth: '3.2 ft', description: 'Deep-buttoned backrest with solid teak frame.' },
  { id: 'int-prod-3', name: 'Scandinavian Armchair', category: 'Furniture', price: 18500, material: 'Wood + Fabric', color: 'Beige', width: '2.5 ft', depth: '2.5 ft', description: 'Light oak legs with a curved backrest.' },
  { id: 'int-prod-4', name: 'Wall-Mounted TV Unit', category: 'Furniture', price: 30000, material: 'Engineered Wood', color: 'Walnut', width: '6 ft', depth: '1.5 ft', description: 'Floating console with cable management.' },
  { id: 'int-prod-5', name: 'Dining Table (6-Seater)', category: 'Furniture', price: 48000, material: 'Solid Wood', color: 'Wood', width: '6 ft', depth: '3 ft', description: 'Extendable table with six upholstered chairs.' },
  { id: 'int-prod-6', name: 'Upholstered King Bed', category: 'Bedroom', price: 72000, material: 'Velvet', color: 'White', width: '6 ft', depth: '6.5 ft', description: 'Tufted headboard with hydraulic storage.' },
  { id: 'int-prod-7', name: 'Wardrobe (4-Door)', category: 'Bedroom', price: 56000, material: 'MDF Laminate', color: 'White', width: '8 ft', depth: '2 ft', description: 'Sliding doors with internal organisers.' },
  // Lighting
  { id: 'int-prod-8', name: 'Pendant Ceiling Light', category: 'Lighting', price: 12000, material: 'Metal + Glass', color: 'Brass', description: 'Dimmable warm-white pendant for dining areas.' },
  { id: 'int-prod-9', name: 'Floor Lamp (Arc)', category: 'Lighting', price: 8500, material: 'Steel', color: 'Black', description: 'Arc floor lamp with marble base.' },
  { id: 'int-prod-10', name: 'Crystal Chandelier', category: 'Lighting', price: 22000, material: 'Crystal', color: 'Clear', description: '8-light chandelier with polished finish.' },
  { id: 'int-prod-11', name: 'LED Cove Lighting Kit', category: 'Lighting', price: 6500, material: 'Aluminium', color: 'White', description: 'Warm 3000K strips for ceiling coves.' },
  // Decor
  { id: 'int-prod-12', name: 'Abstract Wall Art Set', category: 'Decor', price: 9500, material: 'Canvas', color: 'Mixed', description: 'Set of three framed abstract prints.' },
  { id: 'int-prod-13', name: 'Ceramic Table Vase', category: 'Decor', price: 3200, material: 'Ceramic', color: 'Beige', description: 'Hand-finished matte ceramic vase.' },
  { id: 'int-prod-14', name: 'Indoor Plant Bundle', category: 'Decor', price: 4500, material: 'Natural', color: 'Green', description: 'Three low-maintenance indoor plants with pots.' },
  // Flooring
  { id: 'int-prod-15', name: 'Vitrified Floor Tiles', category: 'Flooring', price: 68, material: 'Vitrified', color: 'Grey', width: '2 ft', depth: '2 ft', description: 'Per sq ft — matte finish anti-skid tiles.' },
  { id: 'int-prod-16', name: 'Engineered Wood Flooring', category: 'Flooring', price: 145, material: 'Oak', color: 'Wood', description: 'Per sq ft — click-lock oak veneer planks.' },
  // Wall
  { id: 'int-prod-17', name: 'Textured Wallpaper', category: 'Wall', price: 90, material: 'Vinyl', color: 'Beige', description: 'Per sq ft — washable textured wallpaper.' },
  { id: 'int-prod-18', name: 'Premium Emulsion Paint', category: 'Wall', price: 42, material: 'Acrylic', color: 'White', description: 'Per sq ft — low-VOC washable emulsion.' },
  // Kitchen
  { id: 'int-prod-19', name: 'Modular Kitchen Unit', category: 'Kitchen', price: 95000, material: 'Plywood + Laminate', color: 'Walnut', description: 'Base + tall units with quartz countertop.' },
  { id: 'int-prod-20', name: 'Chimney & Hob Combo', category: 'Kitchen', price: 26000, material: 'Stainless Steel', color: 'Silver', description: 'Auto-clean chimney with 3-burner hob.' },
]